#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook. Running KtLint... "
echo "*********************************************************"

# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# run ktlint apply
./gradlew --quiet ktlintFormat

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    # Add staged file changes to git
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add "$file"
      fi
    done
    #Exit
    exit 0
else
    echo "*********************************************************"
    echo 1>&2 "KtLint found violations it could not fix."
    echo "*********************************************************"
    #Exit
    exit 1
fi
