name: Publish Release

on:
  release:
    types: [published]

jobs:
  prepare-release:
    name: "Prepare Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - uses: robinraju/release-downloader@v1.10
        with:
          tag: ${{ github.ref_name }}
          fileName: 'jetbrains-plugin.zip'
          out-file-path: 'packages/jetbrains-plugin/build/distributions/'
      - name: Publish Plugin In General Availability
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.SVC_DEVTOOLSBOT_TOKEN }}
          JB_PUBLISH_CHANNEL: "ga"
        run: |
          set -e
          
          ./gradlew ":packages:jetbrains-plugin:publishPlugin" $(./gradlew ":packages:jetbrains-plugin:publishPlugin" --dry-run | awk '/^:/ { print "-x" $1 }' | sed '$ d')
          
          git checkout main
          git merge ${{ github.ref_name }}
          git push origin main
          
